<!-- wp:group {"className":"RJE_R001CORP_one_column_items"} -->
<div class="wp-block-group RJE_R001CORP_one_column_items"><!-- wp:snow-monkey-blocks/media-text {"mediaType":"image","mediaPosition":"left","mediaColumnSize":"25","mobileOrder":"image","className":"is-style-RJE_R001CORP_one_column_item"} -->
<div class="wp-block-snow-monkey-blocks-media-text smb-media-text smb-media-text--mobile-image is-style-RJE_R001CORP_one_column_item"><div class="c-row c-row--margin c-row--reverse c-row--middle"><div class="c-row__col c-row__col--1-1 c-row__col--lg-3-4"><h2 class="smb-media-text__title">ブロックパターン制作 <img class="wp-image-1819" style="width: 64px;" src="<?php echo esc_url( RJE_R001CORP_URL ); ?>dist/img/border-short-gray.png" alt=""></h2><div class="smb-media-text__body"><!-- wp:paragraph -->
<p>つれづれなるまゝに、日暮らし、硯にむかひて、心にうつりゆくよしなし事を、そこはかとなく書きつくれば、あやしうこそものぐるほしけれ。つれづれなるまゝに、日暮らし、硯にむかひて、心にうつりゆくよしなし事を、そこはかとなく書きつくれば、あやしうこそものぐるほしけれ。</p>
<!-- /wp:paragraph --></div></div><div class="c-row__col c-row__col--1-1 c-row__col--lg-1-4"><div class="smb-media-text__figure"><img src="<?php echo esc_url( RJE_R001CORP_URL ); ?>dist/img/one-column-items-sample-1.png" alt="" width="536" height="400" class="wp-image-0"/></div></div></div></div>
<!-- /wp:snow-monkey-blocks/media-text -->

<!-- wp:snow-monkey-blocks/media-text {"mediaId":1826,"mediaLink":"https://pattern-dev-ruijinen.local/r001-corp/one_clumn_items/one-column-items-sample-2/","mediaType":"image","mediaColumnSize":"25","mobileOrder":"image","className":"is-style-RJE_R001CORP_one_column_item"} -->
<div class="wp-block-snow-monkey-blocks-media-text smb-media-text smb-media-text--mobile-image is-style-RJE_R001CORP_one_column_item"><div class="c-row c-row--margin c-row--middle"><div class="c-row__col c-row__col--1-1 c-row__col--lg-3-4"><h2 class="smb-media-text__title">ブロックパターン制作 <img class="wp-image-1819" style="width: 64px;" src="<?php echo esc_url( RJE_R001CORP_URL ); ?>dist/img/border-short-gray.png" alt=""></h2><div class="smb-media-text__body"><!-- wp:paragraph -->
<p>つれづれなるまゝに、日暮らし、硯にむかひて、心にうつりゆくよしなし事を、そこはかとなく書きつくれば、あやしうこそものぐるほしけれ。つれづれなるまゝに、日暮らし、硯にむかひて、心にうつりゆくよしなし事を、そこはかとなく書きつくれば、あやしうこそものぐるほしけれ。</p>
<!-- /wp:paragraph --></div></div><div class="c-row__col c-row__col--1-1 c-row__col--lg-1-4"><div class="smb-media-text__figure"><img src="<?php echo esc_url( RJE_R001CORP_URL ); ?>dist/img/one-column-items-sample-2.png" alt="" width="280" height="279" class="wp-image-1826"/></div></div></div></div>
<!-- /wp:snow-monkey-blocks/media-text --></div>
<!-- /wp:group -->