<!-- wp:snow-monkey-blocks/items {"md":3,"lg":3,"className":"RJE_R001CORP_banners is-style-RJE_R001CORP_banners is-height_size_banner"} -->
<div class="wp-block-snow-monkey-blocks-items smb-items RJE_R001CORP_banners is-style-RJE_R001CORP_banners is-height_size_banner"><div class="c-row c-row--margin" data-columns="1" data-md-columns="3" data-lg-columns="3"><!-- wp:snow-monkey-blocks/items-banner {"maskColor":"#000000","maskOpacity":0.5,"imageID":2181} -->
<div class="wp-block-snow-monkey-blocks-items-banner c-row__col"><div class="smb-items__banner smb-items__banner--default"><div class="smb-items__banner__figure"><div class="smb-items__banner__figure__mask" style="background-color:#000000"></div><img src="<?php echo esc_url( RJE_R001CORP_URL ); ?>dist/img/banner-sample-1.jpg" alt="" width="561" height="345" class="wp-image-2181" style="opacity:0.5"/></div><div class="smb-items__banner__body" data-content-position="center-left"><div class="smb-items__banner__body-inner"><div class="smb-items__banner__title">Snow Monkeyサイト構築は<br>我々にお任せください</div></div></div></div></div>
<!-- /wp:snow-monkey-blocks/items-banner -->

<!-- wp:snow-monkey-blocks/items-banner {"maskColor":"#000000","maskOpacity":0.5,"imageID":2182} -->
<div class="wp-block-snow-monkey-blocks-items-banner c-row__col"><div class="smb-items__banner smb-items__banner--default"><div class="smb-items__banner__figure"><div class="smb-items__banner__figure__mask" style="background-color:#000000"></div><img src="<?php echo esc_url( RJE_R001CORP_URL ); ?>dist/img/banner-sample-2.jpg" alt="" width="569" height="379" class="wp-image-2182" style="opacity:0.5"/></div><div class="smb-items__banner__body" data-content-position="center-left"><div class="smb-items__banner__body-inner"><div class="smb-items__banner__title">ブロックパターン制作</div><div class="smb-items__banner__lede">多彩で洗練されたブロックパターン。<br>あなたのサイトを柔軟にカスタマイズ。</div></div></div></div></div>
<!-- /wp:snow-monkey-blocks/items-banner -->

<!-- wp:snow-monkey-blocks/items-banner {"maskColor":"#000000","maskOpacity":0.5,"imageID":2183} -->
<div class="wp-block-snow-monkey-blocks-items-banner c-row__col"><div class="smb-items__banner smb-items__banner--default"><div class="smb-items__banner__figure"><div class="smb-items__banner__figure__mask" style="background-color:#000000"></div><img src="<?php echo esc_url( RJE_R001CORP_URL ); ?>dist/img/banner-sample-1.jpg" alt="" width="561" height="345" class="wp-image-2183" style="opacity:0.5"/></div><div class="smb-items__banner__body" data-content-position="center-left"><div class="smb-items__banner__body-inner"><div class="smb-items__banner__title">類人猿プロジェクト</div></div></div></div></div>
<!-- /wp:snow-monkey-blocks/items-banner --></div></div>
<!-- /wp:snow-monkey-blocks/items -->