<!-- wp:snow-monkey-blocks/section-break-the-grid {"imageID":1903,"imageMediaType":"image","textColor":"#ffffff","imageSize":"","imageMatchHeight":true,"contentSize":"","contentHorizontalPosition":"","contentPadding":"","mobileOrder":"image","fixedBackgroundColor":"#000000","align":"full","className":"RJE_R001CORP_induction is-style-RJE_R001CORP_induction"} -->
<div class="wp-block-snow-monkey-blocks-section-break-the-grid alignfull smb-section smb-section-break-the-grid smb-section-break-the-grid--right smb-section-break-the-grid--mobile-image smb-section-break-the-grid--match-height RJE_R001CORP_induction is-style-RJE_R001CORP_induction" style="color:#ffffff"><div class="smb-section__fixed-background" style="padding-top:0;padding-bottom:0;background-color:#000000"></div><div class="smb-section__inner"><div class="c-container"><div class="smb-section__contents-wrapper smb-section-break-the-grid__contents-wrapper"><div class="c-row c-row--lg-middle"><div class="c-row__col c-row__col--1-1 c-row__col--lg-1-2"><div class="smb-section-break-the-grid__content"><div class="smb-section__header smb-section-break-the-grid__header"><div class="smb-section__subtitle smb-section-break-the-grid__subtitle">採用について</div><h2 class="smb-section__title smb-section-break-the-grid__title">Want to Join?</h2></div><div class="smb-section__body smb-section-break-the-grid__body"><!-- wp:paragraph -->
<p>今、次の目標が見えていますか。<br>分からなくなってしまった、というあなた。<br>私たちと一緒に、働きませんか？<br>きっと、次の一歩を踏み出せるはずです。</p>
<!-- /wp:paragraph -->

<!-- wp:snow-monkey-blocks/buttons -->
<div class="wp-block-snow-monkey-blocks-buttons smb-buttons"><!-- wp:snow-monkey-blocks/btn {"borderRadius":0,"backgroundColor":"#ffffff","textColor":"#ffffff","className":"is-style-ghost"} -->
<div class="wp-block-snow-monkey-blocks-btn smb-btn-wrapper is-style-ghost"><a class="smb-btn" href="" style="background-color:#ffffff;border-radius:0px;border-color:#ffffff"><span class="smb-btn__label" style="color:#ffffff">Read More</span></a></div>
<!-- /wp:snow-monkey-blocks/btn --></div>
<!-- /wp:snow-monkey-blocks/buttons --></div></div></div><div class="c-row__col c-row__col--1-1 c-row__col--lg-1-2"><div class="smb-section-break-the-grid__figure"><img src="<?php echo esc_url( RJE_R001CORP_URL ); ?>dist/img/induction-sample-1.jpg" alt="" width="848" height="592" class="wp-image-1903"/></div></div></div></div></div></div></div>
<!-- /wp:snow-monkey-blocks/section-break-the-grid -->