<!-- wp:snow-monkey-blocks/section {"contentJustification":"left","titleTagName":"none","containerAlign":"full","backgroundVerticalPosition":5,"align":"full","className":"RJE_R001CORP_layered1 is-style-RJE_R001CORP_layered1"} -->
<div class="wp-block-snow-monkey-blocks-section alignfull smb-section smb-section--fit RJE_R001CORP_layered1 is-style-RJE_R001CORP_layered1"><div class="smb-section__inner is-content-justification-left"><div class="c-container alignfull"><div class="smb-section__contents-wrapper"><div class="smb-section__body"><!-- wp:cover {"url":"<?php echo esc_url( RJE_R001CORP_URL ); ?>dist/img/layered-sample-1.jpg","dimRatio":50,"overlayColor":"black","focalPoint":{"x":"0.50","y":0.1},"minHeight":480,"contentPosition":"center center","align":"full","className":"is-light"} -->
<div class="wp-block-cover alignfull is-light" style="min-height:480px"><span aria-hidden="true" class="has-black-background-color wp-block-cover__gradient-background has-background-dim"></span><img class="wp-block-cover__image-background" alt="" src="<?php echo esc_url( RJE_R001CORP_URL ); ?>dist/img/layered-sample-1.jpg" style="object-position:50% 10%" data-object-fit="cover" data-object-position="50% 10%"/><div class="wp-block-cover__inner-container"><!-- wp:paragraph {"align":"center","placeholder":"タイトルを入力...","style":{"typography":{"fontSize":48}},"textColor":"white"} -->
<p class="has-text-align-center has-white-color has-text-color" style="font-size:48px"><strong>Move Forward.</strong></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"align":"center","style":{"typography":{"fontSize":24}},"textColor":"white"} -->
<p class="has-text-align-center has-white-color has-text-color" style="font-size:24px">私たちは、歩み続ける。</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:cover -->

<!-- wp:snow-monkey-blocks/section {"contentsAlignment":"left","contentJustification":"left","containerAlign":"full","fixedBackgroundColor":"#ffffff","fixedBackgroundTexture":"","backgroundText":{"text":"","color":"","fontSize":"","fontSizeSlug":"","lineHeight":"","opacity":0.2,"position":{"top":null,"right":null,"bottom":null,"left":null}}} -->
<div class="wp-block-snow-monkey-blocks-section smb-section smb-section--left smb-section--fit"><div class="smb-section__fixed-background" style="padding-top:0;padding-bottom:0;background-color:#ffffff"></div><div class="smb-section__inner is-content-justification-left"><div class="c-container"><div class="smb-section__contents-wrapper smb-section__contents-wrapper--left"><div class="smb-section__header"><h2 class="smb-section__title">誰も見たことのない進化。<br>類人猿は、想像の及ばないスピードで進んでいきます。</h2><div class="smb-section__lede-wrapper"><div class="smb-section__lede">猿人は原人へ、そして原人は旧人へ。その中から広がったホモ・サピエンスが、長い時間を経て、今を生きる私たちへとつながっていきました。<br>私たちは人間です。そして今、進化を遂げようとしている、<br>Snow Monkeyと共に歩みます。</div></div></div><div class="smb-section__body"></div></div></div></div></div>
<!-- /wp:snow-monkey-blocks/section --></div></div></div></div></div>
<!-- /wp:snow-monkey-blocks/section -->