<!-- wp:snow-monkey-blocks/items {"md":2,"lg":3,"isGlue":true,"className":"RJE_R001CORP_items_with_bg is-style-RJE_R001CORP_items_with_bg"} -->
<div class="wp-block-snow-monkey-blocks-items smb-items smb-items--glue RJE_R001CORP_items_with_bg is-style-RJE_R001CORP_items_with_bg"><div class="c-row" data-columns="1" data-md-columns="2" data-lg-columns="3"><!-- wp:snow-monkey-blocks/items-banner {"maskOpacity":0.5} -->
<div class="wp-block-snow-monkey-blocks-items-banner c-row__col"><div class="smb-items__banner smb-items__banner--default" style="--smb-items--banner--mask-opacity:0.5"><div class="smb-items__banner__figure"><div class="smb-items__banner__figure__mask"></div><img src="<?php echo esc_url( RJE_R001CORP_URL ); ?>dist/img/items-sample-3.jpg" alt="" class="wp-image-0"/></div><div class="smb-items__banner__body" data-content-position="center-left"><div class="smb-items__banner__body-inner"><div class="smb-items__banner__title">タイトルが入ります</div><div class="smb-items__banner__lede">説明文が入ります。リンクと画像も再設定してください。</div></div></div><div class="smb-items__banner__action"><a href="/">タイトルが入ります</a></div></div></div>
<!-- /wp:snow-monkey-blocks/items-banner -->

<!-- wp:snow-monkey-blocks/items-banner {"maskOpacity":0.5} -->
<div class="wp-block-snow-monkey-blocks-items-banner c-row__col"><div class="smb-items__banner smb-items__banner--default" style="--smb-items--banner--mask-opacity:0.5"><div class="smb-items__banner__figure"><div class="smb-items__banner__figure__mask"></div><img src="<?php echo esc_url( RJE_R001CORP_URL ); ?>dist/img/items-sample-4.jpg" alt="" class="wp-image-0"/></div><div class="smb-items__banner__body" data-content-position="center-left"><div class="smb-items__banner__body-inner"><div class="smb-items__banner__title">タイトルが入ります</div><div class="smb-items__banner__lede">説明文が入ります。リンクと画像も再設定してください。</div></div></div><div class="smb-items__banner__action"><a href="/">タイトルが入ります</a></div></div></div>
<!-- /wp:snow-monkey-blocks/items-banner -->

<!-- wp:snow-monkey-blocks/items-banner {"maskOpacity":0.5} -->
<div class="wp-block-snow-monkey-blocks-items-banner c-row__col"><div class="smb-items__banner smb-items__banner--default" style="--smb-items--banner--mask-opacity:0.5"><div class="smb-items__banner__figure"><div class="smb-items__banner__figure__mask"></div><img src="<?php echo esc_url( RJE_R001CORP_URL ); ?>dist/img/items-sample-5.jpg" alt="" width="536" height="330" class="wp-image-0"/></div><div class="smb-items__banner__body" data-content-position="center-left"><div class="smb-items__banner__body-inner"><div class="smb-items__banner__title">タイトルが入ります</div><div class="smb-items__banner__lede">説明文が入ります。リンクと画像も再設定してください。</div></div></div><div class="smb-items__banner__action"><a href="/">タイトルが入ります</a></div></div></div>
<!-- /wp:snow-monkey-blocks/items-banner --></div></div>
<!-- /wp:snow-monkey-blocks/items -->
